# .github/workflows/update-date.yml

name: Update Purchase Date
on:
  schedule:
    - cron: '0 0 * * *'  # 这是每天的凌晨 0 点运行

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Update Date in Script
        run: |
          echo "Updating date in script"
          # 获取当前日期
          date=$(date +'%Y-%m-%d')
          # 替换脚本中的日期内容（假设你要修改的文件是 script.js）
          sed -i "s/DATE_PLACEHOLDER/$date/g" qx/itunestest.js

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add qx/itunestest.js
          git commit -m "Updated date to $date"
          git push
