name: Update Purchase Date

on:
  push:
    branches:
      - main

jobs:
  update_purchase_date:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 赋予写入权限
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Current Time
        id: current_time
        run: |
          NOW=$(date -u +"%Y-%m-%d %H:%M:%S Etc/GMT")
          NOW_MS=$(date +%s000)
          echo "PURCHASE_DATE=$NOW" >> $GITHUB_ENV
          echo "PURCHASE_DATE_MS=$NOW_MS" >> $GITHUB_ENV

      - name: Replace Date in Script
        run: |
          sed -i "s/\$NOW_MS/$PURCHASE_DATE_MS/g" ./qx/iTunestest.js
          sed -i "s/\$NOW/'$PURCHASE_DATE'/g" ./qx/iTunestest.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add /qx/iTunestest.js
          git commit -m "Auto-update purchase date"
          git push
