name: Update Purchase Date

on:
  schedule:
    # 每天在 UTC 时间凌晨 1:00 运行
    - cron: '0 1 * * *'
  workflow_dispatch:  # 允许手动触发工作流程

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Purchase Date
      run: |
        # 获取当前日期和时间
        NOW=$(date -u +"%Y-%m-%d %H:%M:%S Etc/GMT")
        NOW_MS=$(date +%s000)

        # 替换 PURCHASE_DATE 和 PURCHASE_DATE_MS
        sed -i "s/const PURCHASE_DATE_MS = .*/const PURCHASE_DATE_MS = \$NOW_MS;/" ./qx/iTunestest.js
        sed -i "s/const PURCHASE_DATE = .*/const PURCHASE_DATE = '\$NOW';/" ./qx/iTunestest.js

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update purchase date"
        git push
          # 替换脚本中的日期内容（假设你要修改的文件是 script.js）
          sed -i "s/DATE_PLACEHOLDER/$date/g" qx/itunestest.js

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add qx/itunestest.js
          git commit -m "Updated date to $date"
          git push
