# .github/workflows/update-dates.yml

name: Update Date Constants

on:
  schedule:
    - cron: '8 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update date constants
        run: |
          file_path="qx/iTunestest.js"  # Replace with your actual JS file path
          
          # Create a temporary file with the new content
          node -e "
            const fs = require('fs');
            const content = fs.readFileSync('$file_path', 'utf8');
            
            const d = new Date();
            d.setUTCHours(8, 8, 8, 0);
            
            const new_ms = d.getTime().toString();
            const new_date = d.toISOString().replace('T', ' ').replace('.000Z', ' Etc/GMT');
            
            const updated = content
              .replace(/PURCHASE_DATE_MS = \"[0-9]+\"/, 'PURCHASE_DATE_MS = \"' + new_ms + '\"')
              .replace(/PURCHASE_DATE = \"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} Etc\/GMT\"/, 'PURCHASE_DATE = \"' + new_date + '\"');
            
            fs.writeFileSync('$file_path', updated);
          "
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "Update date constants" || exit 0
          git push
